name: Python Prepro

on: [push]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: set up python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            - name: Install dependencies
              run: |
                python -m pip install -U pip
                pip install -r dev_requirements.txt
                pip install -r requirements.txt
                pip install j_realty_api
            - name: Test with pytest
              run: |
                pytest tests/test_unit_citycode_class.py tests/test_unit_proptransactions_class.py
            - name: code formatter
              run: |
                isort .
                black *
